### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [archimag/garbage-pools#4]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by Hellseher** [comment]
Hi Andrey,

I've got the save request to have more metadata to `asd` file or at least some notes in README. I'm about to pack it for Guix as a dependencies of `pgloader->mssql->garbage-pools` and it would be very helpful to have some sort of description.

Thanks.

**Comment by Hellseher** [comment]
@hydandata I think we may mark this issue closed https://github.com/archimag/garbage-pools/pull/5
